#==============================================================#
#                         COLOUR CODES                         #
# &0 (black), &1 (dark blue), &2 (green), &3 (dark aqua),      #
# &4 (red), &5 (purple), &6 (gold), &7 (silver),               #
# &8 (grey), &9 (blue), &a (light green), &b (aqua),           #
# &c (light red), &d (light purple), &e (yellow), &f (white),  #
# &k (magical)                                                 #
# &l (bold), &m (underlined), &n (striked), &o (italic)        #
#==============================================================#

auto-library-update: true
channels:
    enable: true
    server:
        tag: ''
        display-colour: '&f'
        topic: ''
    channel-limit: -1
    messages:
        join: true
        leave: true
logging:
    colouring: true
    debug: none
chat:
    player:
        enable: true
        broadcast: '[&cBroadcast&f] %player: %message'
        emote: '* %player %action'
        whisper: '&5%player whispers: %message'
    server:
        enable: true
        broadcast: '<&4Server&f> %message'
        emote: '* &4Server &f%action'
        whisper: '&4Server &5whispers: %message'
formatting:
    use-custom-format: false
    format: "%tag %prefix%player%suffix: %message"
permissions:
    affixes:
        group:
            guest:
                prefix: '[&8Guest&f]'
             member:
                prefix: '[&7Member&f]'
                suffix: '&2'
            vip:
                prefix: '[&6VIP&f]'
                suffix: '&5'
            mod:
                prefix: '[&1Mod&f]'
            admin:
                prefix: '[&4Admin&f]'
        player:
            titan:
                prefix: '[&4Titan&f]'
            dev:
                prefix: '[&6Dev&f]'
            bukkitdev:
                prefix: '[&1Bukkit]'
                suffix: '&b'
